# -*- coding: utf-8 -*-
"""
Pytest regression tests for the neurodemo simulation models.

These tests compare fresh simulation results against saved .npz reference files.
Reference files are generated by the standalone test app (run_model_tests.py).

Run all:
    pytest neurodemo/tests/test_model_regression.py -v

Skip if no reference:
    Tests are automatically skipped when no reference file exists for a model.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from neurodemo.tests.sim_protocols import (
    compare_results,
    find_oldest_reference,
    load_results,
    run_model_tests,
)

# ── Configuration ──────────────────────────────────────────────────────────────

REFERENCE_DIR = Path(__file__).parent.parent.parent / 'model_results'

V_THRESHOLD = 1e-6    # 1 µV  — IC voltage tolerance
I_THRESHOLD = 1e-13   # 0.1 pA — VC current tolerance

ALL_MODELS = list(['Passive', 'HH AP', 'LG AP'])


# ── Fixtures ───────────────────────────────────────────────────────────────────

@pytest.fixture
def model_regression():
    """
    Callable fixture for model regression testing.  Usable from other test
    modules to assert that a given model hasn't changed numerically.

    Example::

        def test_something(model_regression):
            comp = model_regression('HH AP')
            assert comp['max_V_deviation'] < 1e-6
    """
    def _run(
        model_name: str,
        threshold_v: float = V_THRESHOLD,
        threshold_i: float = I_THRESHOLD,
    ) -> dict:
        ref_path = find_latest_reference(REFERENCE_DIR, model_name)
        if ref_path is None:
            pytest.skip(
                f"No reference file for '{model_name}'. "
                "Run `python run_model_tests.py` and save a reference first."
            )
        reference = load_results(ref_path)
        results   = run_model_tests(model_name)
        comp      = compare_results(reference, results,
                                    threshold_v=threshold_v,
                                    threshold_i=threshold_i)

        assert comp['discrepant_V_points'] == 0, (
            f"IC voltage: {comp['discrepant_V_points']} discrepant points "
            f"(max deviation {comp['max_V_deviation']*1e6:.4f} µV, "
            f"threshold {threshold_v*1e6:.1f} µV)"
        )
        assert comp['discrepant_I_points'] == 0, (
            f"VC current: {comp['discrepant_I_points']} discrepant points "
            f"(max deviation {comp['max_I_deviation']*1e12:.4f} pA, "
            f"threshold {threshold_i*1e12:.2f} pA)"
        )
        return comp

    return _run


# ── Parametrised regression tests ─────────────────────────────────────────────

@pytest.mark.parametrize('model_name', ALL_MODELS)
def test_model_regression(model_name, model_regression):
    """Regression test: each model's IC and VC traces must match the reference."""
    model_regression(model_name)


# ── Smoke tests (no reference needed) ─────────────────────────────────────────

@pytest.mark.parametrize('model_name', ALL_MODELS)
def test_model_runs(model_name):
    """Smoke test: simulation completes without error and returns expected keys."""
    results = run_model_tests(model_name)

    assert 'V_ic'     in results,  "IC voltage traces missing"
    assert 'I_vc'     in results,  "VC current traces missing"
    assert 't_ic'     in results
    assert 't_vc'     in results
    assert results['V_ic'].ndim  == 2
    assert results['I_vc'].ndim  == 2
    assert results['V_ic'].shape[0] == results['I_cmd_ic'].shape[0]
    assert results['I_vc'].shape[0] == results['V_cmd_vc'].shape[0]
    assert results['model'] == model_name
